[package]
name = "RustMQ"
version = "0.1.0"
edition = "2021"

[dependencies.uuid]
version = "1.17.0"
# Lets you generate random UUIDs
features = ["v4"]

[dependencies]
inquire = "0.7.5"
packet = "0.1.4"
